kind: pipeline
name: default

steps:
  - name: check documentation build
    image: rust:1.49-slim-buster
    commands:
      - cargo install mdbook --git https://github.com/Nutomic/mdBook.git --branch localization
            --rev 0982a82 --force --debug
      - mdbook build .
