kind: pipeline
name: default

steps:
  - name: check documentation build
    image: rust:1.49-slim-buster
    commands:
      - apt install git
      - git submodule init
      - git submodule update --recursive --remote
      - ./build.sh
