kind: pipeline
name: default

steps:
  - name: fetch git submodules
    image: alpine/git
    commands:
      - git submodule init
      - git submodule update --recursive --remote

  - name: check documentation build
    image: rust:1.49-slim-buster
    commands:
      - apt update
      - apt install git --yes
      - ./build.sh
