clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true
      submodule_update_remote: true
pipeline:
  check_formatting:
    image: alpine:3
    commands:
      - apk add prettier --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing
      - prettier -c src

  check_documentation_build:
    image: rust:1.61-slim-buster
    commands:
      - cargo install mdbook --git https://github.com/Ruin0x11/mdBook.git --branch localization
            --rev 9d8147c --force --debug
      - apt-get update
      - apt-get install git curl -y
      - ./update-includes.sh
      - mdbook build .

  dead_links:
    image: becheran/mlc:latest
    commands:
      - mlc src/en --ignore-links "*localhost*" --ignore-links "*127.0.0.1*" --ignore-links /api
